require 'faraday'
require 'faraday_middleware'
require 'hashie'

require 'exist/version'
require 'exist/authentication'
require 'exist/attributes'
require 'exist/attribute_list'
require 'exist/insight'
require 'exist/insight_list'
require 'exist/average'
require 'exist/average_list'
require 'exist/correlation'
require 'exist/correlation_list'
require 'exist/user'
require 'exist/api'
